config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  constraints Constraints::DomainConstraint.new(Settings[Rails.env][:it_way]) do
    mount Tramway::Conference::Engine => '/'
    mount Tramway::Api::Engine, at: '/api', as: :it_way_api

    get '/youtube-callback' => 'youtube_callbacks#create'
    get '/:id' => 'shortener/shortened_urls#show'

    scope module: :it_way do
      resources :certificates, only: :show
      resources :podcasts, only: :show
    end
  end

  constraints Constraints::DomainConstraint.new(Settings[Rails.env][:kalashnikovisme]) do
    root to: 'kalashnikovisme/web/welcome#index'

    mount Tramway::Admin::Engine, at: '/admin', as: :kalash_admin
    mount Tramway::Auth::Engine, at: '/auth', as: :kalash_auth
  end

  constraints Constraints::DomainConstraint.new(Settings[Rails.env][:tramway_dev]) do
    root to: 'tramway_dev/web/welcome#index'

    mount Tramway::Admin::Engine, at: '/admin'
    mount Tramway::Auth::Engine, at: '/auth'
  end

  constraints Constraints::DomainConstraint.new(Settings[Rails.env][:engineervol]) do
    root to: 'engineervol/web/welcome#index'

    mount Tramway::Admin::Engine, at: '/admin', as: :vol_admin
    mount Tramway::Auth::Engine, at: '/auth', as: :vol_auth
  end

  constraints Constraints::DomainConstraint.new(Settings[Rails.env][:purple_magic]) do
    root to: 'purple_magic/web/welcome#index'

    mount Tramway::Admin::Engine, at: '/admin', as: :purple_magic_admin
    mount Tramway::Auth::Engine, at: '/auth', as: :purple_magic_auth

    namespace :purple_magic do
      namespace :api do
        namespace :v1 do
          namespace :estimation do
            resources :projects, only: :update
          end
          namespace :leopold do
            resources :messages, only: :create
          end
        end
      end
    end
  end

  constraints Constraints::DomainConstraint.new(Settings[Rails.env][:benchkiller]) do
    root to: 'benchkiller/web/welcome#index'

    namespace :benchkiller do
      namespace :web do
        resources :sessions, only: [:create]
        get 'sign_out', to: 'sessions#destroy'
        resources :offers, only: :index
        resources :companies, only: %i[show edit update]
        resources :deliveries, only: %i[new create show edit update] do
          member do
            get :run_process
          end
        end
      end

      namespace :api do
        resources :user_tokens, only: :create
        resources :offers, only: :index
        resources :regions, only: :index
      end
    end

    mount Tramway::Admin::Engine, at: '/admin', as: :benchkiller_admin
  end

  constraints Constraints::DomainConstraint.new(Settings[Rails.env][:red_magic]) do
    root to: 'red_magic/web/welcome#index'

    mount Tramway::Admin::Engine, at: '/admin', as: :red_magic_admin
    mount Tramway::Auth::Engine, at: '/auth', as: :red_magic_auth
    mount Tramway::Page::Engine, at: '/page', as: :red_magic
    mount Tramway::Api::Engine, at: '/api', as: :red_magic_api

    namespace :red_magic do
      namespace :api do
        namespace :v1 do
          namespace :podcast do
            resources :episodes, only: :update do
              member do
                patch :video_is_ready
              end
            end
          end
          namespace :content do
            resources :stories, only: :update
          end
          namespace :estimation do
            resources :projects, only: :update
          end
          resources :time_logs, only: :index
        end
      end
    end
  end
end

app/models/benchkiller/company.rb
# frozen_string_literal: true

class Benchkiller::Company < ApplicationRecord
  has_many :companies_users, class_name: 'Benchkiller::CompaniesUser'
  has_many :users, through: :companies_users, class_name: 'Benchkiller::User'

  store_accessor :data, :portfolio_url
  store_accessor :data, :company_url
  store_accessor :data, :email
  store_accessor :data, :phone

  validates :title, uniqueness: true

  scope :benchkiller_scope, ->(_user) { all }
  %i[unviewed approved declined].each do |review_state|
    scope review_state, -> { where review_state: review_state }
  end

  include BotTelegram::BenchkillerBot::AdminFeatures

  after_create do |company|
    send_companies_creating_to_admin_chat company
  end

  after_save do |company|
    send_companies_changes_to_admin_chat company
  end

  search_by :title

  aasm :review_state do
    state :unviewed, initial: true
    state :approved
    state :declined

    event :approve do
      transitions from: :unviewed, to: :approved

      after do
        save!
        user = users.first
        Benchkiller::SendApprovementMessageWorker.perform_async user.id
      end
    end

    event :decline do
      transitions from: :unviewed, to: :declined

      after do
        save!
        user = users.first
        Benchkiller::SendRejectionMessageWorker.perform_async user.id
      end
    end

    event :return_to_unviewed do
      transitions from: %i[approved declined], to: :unviewed
    end
  end

  def user_is?(user)
    users.include? user
  end
end

app/models/find_meds/company.rb
class FindMeds::Company < ApplicationRecord
  ATTRIBUTES = {
    name: 'Name',
  }
end

app/controllers/benchkiller/web/companies_controller.rb
# frozen_string_literal: true

class Benchkiller::Web::CompaniesController < Benchkiller::Web::ApplicationController
  def show
    @company = ::Benchkiller::CompanyDecorator.new ::Benchkiller::Company.find_by uuid: params[:id]
    @company_has_user = @company.user_is? current_user.model
  end

  def edit
    @company_form = ::Benchkiller::Web::CompanyForm.new ::Benchkiller::Company.find_by uuid: params[:id]
  end

  def update
    @company_form = ::Benchkiller::Web::CompanyForm.new ::Benchkiller::Company.find_by uuid: params[:id]
    if @company_form.submit params[:benchkiller_company]
      redirect_to benchkiller_web_company_path(@company_form.model.uuid)
    else
      render :edit
    end
  end
end

app/helpers/benchkiller/companies_helper.rb
# frozen_string_literal: true

module Benchkiller::CompaniesHelper
  def companies_title
    content_for :title do
      if @company.present?
        "#{@company.title} | Benchkiller"
      elsif @company_form.present?
        "#{@company_form.model.title} | Benchkiller"
      else
        "#{t('.title')} | Benchkiller"
      end
    end
  end
end

app/views/benchkiller/web/companies/edit.html.haml
- companies_title
= simple_form_for @company_form, url: benchkiller_web_company_path(@company_form.model.uuid), method: :patch do |f|
  = f.label :title, @company_form.model.class.human_attribute_name(:title)
  = f.input :title, as: :string, label: false

  = f.label :company_url, @company_form.model.class.human_attribute_name(:company_url)
  = f.input :company_url, as: :string, label: false

  = f.label :email, @company_form.model.class.human_attribute_name(:email)
  = f.input :email, as: :string, label: false

  = f.label :portfolio_url, @company_form.model.class.human_attribute_name(:portfolio_url)
  = f.input :portfolio_url, as: :string, label: false

  = f.label :place, @company_form.model.class.human_attribute_name(:place)
  = f.input :place, as: :string, label: false

  = f.label :phone, @company_form.model.class.human_attribute_name(:phone)
  = f.input :phone, as: :string, label: false

  = f.label :regions_to_cooperate, @company_form.model.class.human_attribute_name(:regions_to_cooperate)
  = f.input :regions_to_cooperate, as: :string, label: false

  = f.button :submit, 'Изменить', class: 'btn btn-success'

app/views/benchkiller/web/companies/show.html.haml
- companies_title
%h1.mb-4
  = @company.title
  - if @company_has_user
    = link_to fa_icon('pencil-alt'), edit_benchkiller_web_company_path(@company.uuid), class: 'btn btn-warning'

%hr
.row
  .col
    .media
      %h3.mr-3
        = fa_icon :history
      .media-body
        %h5.mt-0
          Дата регистрации на Benchkiller
        %p
          = @company.created_at.strftime('%d.%m.%Y')
  .col
    .media
      %h3.mr-3
        = fa_icon :link
      .media-body
        %h5.mt-0
          Сайт компании
        %p
          = link_to @company.company_url, @company.company_url

.row
  .col
    .media
      %h3.mr-3
        = fa_icon :city
      .media-body
        %h5.mt-0
          Регион
        %p
          = @company.place
  .col
    .media
      %h3.mr-3
        = fa_icon :envelope
      .media-body
        %h5.mt-0
          Email
        %p
          = mail_to @company.email
.row
  .col
    .media
      %h3.mr-3
        = fa_icon :portrait
      .media-body
        %h5.mt-0
          Портфолио
        %p
          = link_to @company.portfolio_url, @company.portfolio_url
  .col
    .media
      %h3.mr-3
        = fa_icon :phone
      .media-body
        %h5.mt-0
          Телефон
        %p
          - if @company.phone.present?
            = tel_tag @company.phone
          - else
            Не опубликован

.row
  .col
    .media
      %h3.mr-3
        = fa_icon :handshake
      .media-body
        %h5.mt-0
          Регионы сотрудничества
        %p
          = @company.regions_to_cooperate